# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
stages:
 - stage: Build
   jobs:
   - job: Build

     pool:
       vmImage: 'windows-latest'

     variables:
       solution: '**/*.sln'
       buildPlatform: 'Any CPU'
       buildConfiguration: 'Release'

     steps:
     - task: NuGetToolInstaller@1

     - task: NuGetCommand@2
       inputs:
         restoreSolution: '$(solution)'

     - task: VSBuild@1
       inputs:
         solution: '$(solution)'
         msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
         platform: '$(buildPlatform)'
         configuration: '$(buildConfiguration)'
     
     - task: DotNetCoreCLI@2
       displayName: Publish
       inputs:
         command: publish
         publishWebProjects: True
         arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)'
         zipAfterPublish: True

     - task: CopyFiles@2
       displayName: 'Copy Files to: $(build.artifactStagingDirectory)/DropArmTemplates'
       inputs:
         SourceFolder: DemoApp/Manifest
         TargetFolder: '$(build.artifactStagingDirectory)/DropArmTemplates'

     - task: PublishBuildArtifacts@1
       displayName: 'Publish Artifact'
       inputs:
         PathtoPublish: '$(build.artifactStagingDirectory)'
       condition: succeededOrFailed()

 - stage: Deploy
   jobs:
   - job: Deploy
     pool:
       vmImage: 'vs2017-win2016'
     variables:
       AppServiceName: 'demo-yaml1'
     steps:
     - task: DownloadBuildArtifacts@0
       inputs:
         buildType: 'current'
         downloadType: 'single'
         artifactName: '_dotnetcoresampleapplication-ASP.NET Core-CI'
         downloadPath: '$(System.ArtifactsDirectory)'
     - task: AzureRmWebAppDeployment@4
       inputs:
         ConnectionType: 'AzureRM'
         azureSubscription: 'Free Trial(8bc354b4-f372-41ce-a6c2-856ab22f5fcf)'
         appType: 'webApp'
         WebAppName: 'demo-yaml1'
         packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
